<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.542">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Ambiente de todos, ambiente para todos: ativismo ambiental como parte da solução">

<title>Democracia Ambiental - Multidimensionalidade do sofrimento social em desastres relacionados a eventos hidrológicos opostos: um estudo comparado dos discursos jornalísticos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Segurança pública_efetividade da polícia militar.html" rel="next">
<link href="./Direitos humanos e a proteção do meio ambiente.html" rel="prev">
<link href="./logo-evento-marrom.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>


<link rel="stylesheet" href="custom.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./gt3e4_diversidade-e-meio-ambiente_saneamento-basico.html">GT 3 – Diversidade e meio ambiente e GT 4 – Ativismo e saneamento básico</a></li><li class="breadcrumb-item"><a href="./Multidimensionalidade do sofrimento social.html">Multidimensionalidade do sofrimento social em desastres relacionados a eventos hidrológicos opostos: um estudo comparado dos discursos jornalísticos</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./logo-evento-marrom.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Democracia Ambiental</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ceda-selo-editorial/iii-encontro-democracia-ambiental/blob/c54d0292532fb9f3e20a248633eea4e796a57c39/e-book_ceda.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-download"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apresentação</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./gt1_ativismo-climatico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GT 1 – Ativismo climático</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Alexandra Aragão.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Palestra de abertura do GT 1 – Ativismo climático</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A viabilidade econômica dos SAF’s.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A viabilidade econômica dos SAF’s no mercado de aviação</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Gestão de riscos climáticos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gestão de riscos climáticos: estudo da cidade de Santos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Mudanças climáticas em nível local.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mudanças climáticas em âmbito local: a pertinência da política climática em nível municipal</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./gt2_ativismo-e-agua.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GT 2 – Ativismo e água</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Direito transnacional e o novo constitucionalismo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Direito transnacional e o novo constitucionalismo latino-americano: o reconhecimento dos rios como ente vivo e portador de direitos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Governança das águas superficiais no Maranhão.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Governança das águas superficiais no maranhão: análise da qualidade na bacia do rio Itapecuru, Maranhão e a urgência de ações para evitar a crise hídrica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Logística Reversa da Água.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Logística Reversa da Água: um caminho para sustentabilidade</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Os caminhos da Água e suas relações.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Os caminhos da Água e suas relações: um diálogo entre Brasil e Noruega</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reflexões sobre a participação social.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reflexões sobre a participação social para a implementação da Política Estadual de Recursos Hídricos no Maranhão, pré Amazônia brasileira</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./gt3e4_diversidade-e-meio-ambiente_saneamento-basico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GT 3 – Diversidade e meio ambiente e GT 4 – Ativismo e saneamento básico</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ozelito Possidonio de Amarante Junior.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Palestra de abertura do GT 3 – Diversidade e meio ambiente</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Marcel Britto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Palestra de abertura do GT 4 – Ativismo e saneamento básico</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ativismo judicial na defesa do meio ambiente.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ativismo judicial na defesa do meio ambiente: Estado Democrático de Direito da Constituição Federal de 1988</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Desafios de proteção social adaptativa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Desafios de proteção social adaptativa no contexto brasileiro de crises sinérgicas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Diagnóstico do abastecimento de água e tratamento de esgoto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Diagnóstico do abastecimento de água e tratamento de esgoto em empreendimentos e residências tangentes à orla de São Luís/MA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Direitos humanos e a proteção do meio ambiente.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Direitos humanos e a proteção do meio ambiente: notas sobre o mercado interno regulado de carbono no Brasil</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Multidimensionalidade do sofrimento social.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Multidimensionalidade do sofrimento social em desastres relacionados a eventos hidrológicos opostos: um estudo comparado dos discursos jornalísticos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Segurança pública_efetividade da polícia militar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Segurança pública: efetividade da polícia militar por meio da ostensividade e do militarismo versus políticas públicas de policiamento comunitário em Manaus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Solo-cinza para pavimentos rodoviários.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Solo-cinza para pavimentos rodoviários</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./gt5_ativismo-judicial-e-meio-ambiente.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GT 5 – Ativismo judicial e meio ambiente</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Importância da prova pericial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Importância da prova pericial para a liquidação da sentença coletiva ambiental</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./gt6_ativismo-e-o-planejamento-urbano.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GT 6 – Ativismo e o planejamento urbano</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A mobilização da sociedade civil pela preservação.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A mobilização da sociedade civil pela preservação da memória dos bairros no município de São Paulo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Conselhos participativos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conselhos participativos: inclusão e paradoxos da gestão democrática das cidades</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Instrumentos de política pública de desperdício alimentar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Instrumentos de política pública de desperdício alimentar nos países da América do Sul: um olhar sobre a gestão urbana sustentável</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Mudanças climáticas e sustentabilidade nas comunidades.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mudanças climáticas e sustentabilidade nas comunidades: iniciativas para alcançar o ODS 11 sob a luz do Projeto Pescadores de Histórias, Cubatão-SP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ocupação e grandes projetos econômicos na Amazônia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ocupação e grandes projetos econômicos na Amazônia: a formação de campos de disputas e o avanço das fronteiras a partir de políticas do Estado brasileiro</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./gt7_populacoes_tradicionais-ambiente-e-ativismo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GT 7 – Populações tradicionais, ambiente e ativismo</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Carolina de Albuquerque.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Palestra de abertura do GT 7 – Populações tradicionais, ambiente e ativismo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A (in)constitucionalidade da Lei n.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A (in)constitucionalidade da Lei n.º 6.001/1973 quanto ao usufruto exclusivo das riquezas naturais e a mineração de pequena escala em terras indígenas em São Gabriel da Cachoeira/AM: um instrumento econômico como alternativa à exploração predatória para sobrevivência física e cultural?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Exploring co-creation, visual law and legal design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploring Co-creation, Visual Law and Legal Design to bridge legal understanding to groups in vulnerable situations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lei do transporte zero em MT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lei do transporte zero em MT: ausência de democracia ambiental, ausênciado direito a comunicação e a negação do modo de vida ribeirinho</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./O acesso à saúde como requisito fundamental.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">O acesso à saúde como requisito fundamental de liberdade das populações ribeirinhas do Amazonas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Paradoxos das energias renováveis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paradoxos das energias renováveis: os significados psicossocioambientais de comunidades afetadas por atividades mineradoras: A exploração de lítio em Boticas, Portugal, como estudo de caso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reparação Comunitária Integral em território da pesca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reparação Comunitária Integral em território da pesca artesanal no enfrentamento ao desastre-crime do petróleo e da COVID-19</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Restauração ecológica em uma comunidade de matriz africana.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Restauração ecológica em uma comunidade de matriz africana praticante do Candomblé (Araras, SP, Brasil)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./gt8_ativismo-normativo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GT 8 – Ativismo normativo</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ativismo normativo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ativismo normativo: marco regulatório de bioinsumos no Brasil</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Políticas públicas de participação social no Brasil.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Políticas públicas de participação social no Brasil: instrumentos e contradições do governo federal</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><strong>Introdução</strong></a></li>
  <li><a href="#material-e-métodos" id="toc-material-e-métodos" class="nav-link" data-scroll-target="#material-e-métodos"><strong>Material e Métodos</strong></a></li>
  <li><a href="#resultados-e-discussão" id="toc-resultados-e-discussão" class="nav-link" data-scroll-target="#resultados-e-discussão"><strong>Resultados e Discussão</strong></a></li>
  <li><a href="#conclusões" id="toc-conclusões" class="nav-link" data-scroll-target="#conclusões"><strong>Conclusões</strong></a></li>
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências"><strong>Referências</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./gt3e4_diversidade-e-meio-ambiente_saneamento-basico.html">GT 3 – Diversidade e meio ambiente e GT 4 – Ativismo e saneamento básico</a></li><li class="breadcrumb-item"><a href="./Multidimensionalidade do sofrimento social.html">Multidimensionalidade do sofrimento social em desastres relacionados a eventos hidrológicos opostos: um estudo comparado dos discursos jornalísticos</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Multidimensionalidade do sofrimento social em desastres relacionados a eventos hidrológicos opostos: um estudo comparado dos discursos jornalísticos</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="multidimensionality-of-social-suffering-in-disasters-related-to-opposite-hydrological-events-a-comparative-study-of-journalistic-discourses" class="level4">
<h4 class="anchored" data-anchor-id="multidimensionality-of-social-suffering-in-disasters-related-to-opposite-hydrological-events-a-comparative-study-of-journalistic-discourses"><strong><em>Multidimensionality of social suffering in disasters related to opposite hydrological events: a comparative study of journalistic discourses</em></strong></h4>
<hr>
<div class="text-end">
<p><a href="http://lattes.cnpq.br/8854352780107387">Meire Cristiane Bortolato FREGONESI</a><sup>1</sup>; <a href="http://lattes.cnpq.br/7161606146208875">Norma VALENCIO</a><sup>2</sup></p>
<p><sup>1</sup> UFSCar/PPGCAm – <a href="mailto:crisbortolato@gmail.com">crisbortolato@gmail.com</a></p>
<p><sup>2</sup> UFSCar/DCAm e PPGCAm – <a href="mailto:norma.valencio@ufscar.br">norma.valencio@ufscar.br</a></p>
</div>
<hr>
<p><strong>RESUMO</strong></p>
<p>Ambos, desastres relacionados à precipitação pluviométrica intensa e à escassez hídrica, produzem danos e perdas multidimensionais para os grupos sociais afetados assim como exigem medidas de mitigação tempestivas por parte das autoridades públicas constituídas. Ocorre que tanto a natureza dos danos e perdas quanto das providências institucionais a serem tomadas são distintas diante da ocorrência destes eventos de características ambientais opostas. Nesse estudo, de caráter descritivo e sob um prisma socioambiental, aborda-se o conteúdo de registros jornalísticos, oriundos de diferentes mídias profissionais, que se debruçam sobre casos recentes deste par de opostos. Trata-se dos casos ocorridos, respectivamente, no município de Socorro (emergência decretada em razão de inundações) e de Artur Nogueira (emergência decretada em razão de colapso de abastecimento hídrico), ambos localizados na Região Administrativa de Campinas, estado de São Paulo. Conclui-se que o olhar midiático convencional é ainda tacanho e repetitivo na exploração da ampla gama de aspectos que essas situações dramáticas ocasionam na vida cotidiana dos grupos sociais afetados, embora dê razoáveis pistas da variabilidade de situações desafiadoras enfrentadas pelos grupos sociais afetados.</p>
<p><strong><em>Palavras-chave:</em></strong> desastre; crise hídrica; inundações.</p>
<p><strong>ABSTRACT</strong></p>
<p>Both, disasters related to heavy rainfall groups and water scarcity, produce multidimensional damage and losses for the affected social groups, and require timely mitigation measures by the public authorities. However, both the nature of these damages and losses and the institutional measures to be taken are distinct in the face of the occurrence of these events with opposite environmental characteristics. This study, of a descriptive nature and from a socio-environmental perspective, addresses the content of journalistic records, originating from different professional media outlets, which focus on recent cases of this pair of opposites. These are the cases that occurred, respectively, in the municipalities of Socorro (emergency declared due to flooding) and Artur Nogueira (emergency declared due to collapse of water supply), both located in the Administrative Region of Campinas, São Paulo state. It is concluded that the conventional media perspective is still narrow-minded and repetitive in exploring the wide range of aspects that these dramatic situations cause in the daily lives of the affected social groups, although it provides reasonable clues about the variability of challenging situations faced by the affected social groups.</p>
<p><strong><em>Keywords:</em></strong> disaster; water crisis; floods.</p>
</section>
<section id="introdução" class="level3">
<h3 class="anchored" data-anchor-id="introdução"><strong>Introdução</strong></h3>
<p>Os desastres associados ao excesso e à escassez hídrica estão se tornando mais recorrentes e intensos em várias cidades e estados do país, inclusive no estado de São Paulo, considerado o mais desenvolvido economicamente dentre as Unidades Federativas do país. Exemplos recentes destes acontecimentos socioambientais desafiadores, que estão se tornando frequente, foram as decretações de emergência havidas nos municípios paulistas de Socorro, em 2023, associada a uma intensa precipitação pluviométrica, e de Artur Nogueira, em 2024, associada à estiagem prolongada. Ao se inserirem em tais contextos hidrológicos adversos, as comunidades afetadas nestes dois municípios tiveram que lidar com disjunções em sua vida cotidiana, o que suscitou sofrimento social para os seus membros.</p>
<p>Como ocorre em contextos afins, cada qual experienciou os seus desafios e a sua dor, bem como se compadeceu das agruras alheias, de um modo particular, em conformidade com os componentes intersubjetivos dos envolvidos; o tipo de vínculo social estabelecido entre eles; o repertório de sentidos que os une ou os distingue; a natureza específica da articulação entre os elementos constitutivos dos prejuízos, perdas e danos havidos; por fim, coadunado com as demais características socioculturais e comportamentais que definem o contexto socioespacial e os modos/estilos de vida implicados (TURNER, 2012; VALENCIO e VALENCIO, 2018a). Além desses variados compósitos na trama individual, familiar e comunitária de vivenciamento de um desastre, é suposto que a especificidade do evento ameaçante, durante e após a sua plena manifestação, corresponda a agravos igualmente peculiares, caso não haja o acionamento tempestivo de estratégias compatíveis na redução dos riscos. Nos casos em tela, ocorridos em Socorro e em Artur Nogueira, supõe-se que os atributos hidrológicos tão díspares dos eventos havidos – de um lado, inundações provocadas por precipitação pluviométrica concentrada/intensa e, de outro, escassez hídrica prolongada e medidas tempestivas de racionamento no abastecimento público – tenham suscitado conjuntos consideravelmente distintos de prejuízos, perdas e danos nestas localidades, diferenciando, portanto, o tipo de sofrimento social que acometeram os seus membros. Uma das formas de constatar a existência ou não de tais distinções entre o conjunto de agravos havidos é através dos registros jornalísticos disponíveis acerca dos referidos casos. Porém, o conteúdo desses registros pode guardar um paradoxo, qual seja: na medida em que informa e esclarece o público sobre as ocorrências, destacando tal ou qual aspecto desafiador ou dramático vivenciado pela comunidade afetada, também é passível de produzir enquadramentos genéricos e padronizados que invisibilizam e/ou retiram a complexidade dos acontecimentos publicizados, pasteurizando-os.</p>
<p>Ocorre que, na fase aguda destes tipos opostos de contexto hidrológico, a grande mídia e as mídias profissionais locais têm acesso privilegiado tanto aos grupos sociais afetados quanto às autoridades constituídas, podendo, assim, extrair ‘furos’ jornalísticos, cuja possibilidade de maior repercussão subsidiará a formação de uma opinião pública homogeneizada a esse respeito. Não raro, para ter acesso ao que costuma ser tecnicamente denominado, pelas defesas civis, como ‘teatro de operações’ – isto é, a zona quente dos acontecimentos –, repórteres fazem acordos tácitos com as autoridades para que estas lhes franqueiem a presença e o registro inédito de imagens e de vozes locais, ao custo de não lhes imputar – ao menos, não com a severidade necessária – eventuais responsabilidades por negligência, imprudência ou imperícia (SCALON; ALLDRED, 1982; VALENCIO, N. e VALENCIO, A., 2018b).</p>
<p>Diante isso, esse estudo propõe descrever o conjunto de elementos de prejuízos, perdas e danos que os registros jornalísticos exploraram, em suas notícias e reportagens, sobre os supramencionados casos ocorridos nos municípios de Socorro e de Artur Nogueira, a fim de explicitar quais similares e/ou distinções entre os agravos havidos nestes casos o discurso jornalístico capturou.</p>
<p>O caso das inundações ocorridas em Socorro, com grande intensidade, em 21 de janeiro de 2024 – após uma ocorrência prévia similar no final do ano de 2023 –, e da crise hídrica pela qual Artur Nogueira atravessou no segundo semestre de 2024 – deflagrada em 30 de julho do referido ano – produziram agravos multifacetados e acima da capacidade de suporte das autoridades locais, levando-as a decretar emergência. O acionamento institucional desse dispositivo legal, que tornou público a situação dramática experenciada pela comunidade e autoridades locais, colocou-os em circunstâncias excepcionais e coletivas de exposição de seus infortúnios súbitos e involuntários, chamando a atenção da mídia profissional para explorar mais detidamente os acontecimentos.</p>
</section>
<section id="material-e-métodos" class="level3">
<h3 class="anchored" data-anchor-id="material-e-métodos"><strong>Material e Métodos</strong></h3>
<p>Apoiando-se numa revisão de literatura do campo crítico das Humanidades e Ciências Sociais, particularmente das áreas de Sociologia dos Desastres e de Comunicação Social, fez-se um levantamento de notícias e reportagens jornalísticas dos casos supramencionados a fim de lograr uma identificação preliminar de quais atores e dimensões da vida social foram afetados nestas crises relacionadas a eventos opostos, naquilo que tange à natureza hidrológica implicada. Procurou-se aglutinar os gêneros textuais principais do universo jornalístico – quais sejam, reportagens e notícias –, coletando, via <em>website</em>, como através da Plataforma Google, um número equivalente de matérias, em ambos os gêneros, sobre ambos os casos acima. Procurou-se, ainda, variar entre matérias audiovisuais e escritas e garantir diversidade das fontes profissionais consultadas.</p>
<p>Uma vez identificado o link destes registros, especificados nas referências deste estudo, fez-se a escuta, visualização e/ou a leitura dos mesmos a fim de apreender os elementos-chave dos desafios enfrentados localmente, devido às mencionadas circunstâncias adversas, bem como as providências públicas tomadas.</p>
</section>
<section id="resultados-e-discussão" class="level3">
<h3 class="anchored" data-anchor-id="resultados-e-discussão"><strong>Resultados e Discussão</strong></h3>
<p>Os desastres relacionados à água têm sido um dos grandes desafios planetários, sejam eles relacionados à escassez hídrica ou às inundações. O Brasil, considerado uma nação emergente e, ainda, por conta da sua vastidão territorial e pujança econômica, é um dos países que não está isento desses desafios. Ao contrário, sofre inúmeras ocorrências relacionadas às secas, estiagens prolongadas e precipitações pluviométricas intensas e seus desdobramentos como incêndios florestais, escassez hídrica, enxurradas, inundações e escorregamentos de terra, ocorrências que se manifestam simultaneamente, porém, em porções federativas ou macrorregionais distintas no abrangente território nacional.</p>
<p>Nesse contexto nacional, o estado de São Paulo é considerado o mais desenvolvido economicamente e cientificamente, o que leva à suposição de um alto nível de bem-estar coletivo, tornando-o mais providente e resistente no enfrentamento de conhecidos e monitorados fatores de ameaça provindos da dinâmica de sistemas naturais, especialmente, aquelas relacionados à água doce, como os que mencionados fenômenos de estresse hídrico e de inundações. Entretanto, essa suposição deve ser colocada sob inspeção, não apenas porque uma expressiva crise hídrica ocorreu nessa unidade federativa, no ano de 2014, resultante da intersecção entre seca e desmatamento (MARENGO e ALVES, 2015), como também chuvas intensas, como as relacionadas a anomalias climáticas, precipitaram em localidades do estado de São Paulo, tal como ocorreu, no início ano de 2023, no município de São Sebastião (BIASOLI, F. e BIASOLI, S.; 2024), casos nos quais os prejuízos, perdas e danos consideráveis parecem não ter deixado as autoridades constituídas imbuídas de um senso de urgência devido quanto à adoção de medidas preparativas mais disseminadas e eficazes.</p>
<p>A relação do desenvolvimento econômico e da acelerada urbanização com as perpetuações de injustiças distributivas no acesso aos bens vitais, como água e moradia digna, também se reflete no modo como o excesso ou a falta de água são equacionados e manejados pelas autoridades competentes; não raro, replicam os mesmos vieses setoriais e de classe no atendimento às demandas recebidas (KOWARICK, 2009; HELLER, 2022). O contexto de aceleração das mudanças climáticas entra como o mais recente fator que pode vir a aumentar a frequência e intensidade de ambas as anomalias hidrometeorológicas mencionadas, o que exige uma mudança das concepções de gestão hídrica – incluindo os infrassistema de drenagem urbana – e incremento da mobilização social para exigi-lo (TUNDISI, 2013; HELLER, 2022). A mobilização social em torno do referido assunto é, ainda, pálida, sobretudo em se tratando de municípios paulistas interioranos, de pequeno e médio porte, cujo perfil cultural e político dominante tende a ser conservador (BRAGA, COSTA e FERNANDES, 2018).</p>
<p>O município de Socorro, no interior paulista, tem 449,029 km2. No ano de 2022, contava com uma população de 40.122 pessoas e densidade demográfica de 89,35 hab/km2. Em 2023, a receita municipal constava como sendo de R$ 199.139.714,12<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. O referido município se localiza a uma latitude 22º35'29"&nbsp;<a href="https://pt.wikipedia.org/wiki/Sul">sul</a>&nbsp;e a uma&nbsp;<a href="https://pt.wikipedia.org/wiki/Longitude">longitude</a>&nbsp;46º31'44"&nbsp;<a href="https://pt.wikipedia.org/wiki/Oeste">oeste</a>, estando a uma altitude de 752 metros, ficando às margens do&nbsp;<a href="https://pt.wikipedia.org/wiki/Rio_do_Peixe_(afluente_do_rio_Mojigua%C3%A7u)">rio do Peixe</a>&nbsp;e na&nbsp;<a href="https://pt.wikipedia.org/wiki/Serra_da_Mantiqueira">Serra da Mantiqueira</a>. Atualmente, a economia do município está voltada para o setor de confecções (malharias), agricultura, pecuária e turismo ecológico, esporte de aventura, cicloturismo e mototurismo. Socorro é um dos dezenove municípios paulistas considerados estâncias hidrominerais pelo&nbsp;<a href="https://pt.wikipedia.org/wiki/S%C3%A3o_Paulo_(estado)">Estado de São Paulo</a>, por cumprirem determinados pré-requisitos definidos por Lei Estadual. Tal&nbsp;<em>status</em>&nbsp;garante a esses municípios uma verba maior por parte do Estado para a promoção do turismo regional. O município adquire, também, o direito de agregar, junto ao seu nome, o título de&nbsp;Estância Hidromineral, termo pelo qual passa a ser designado tanto pelo expediente municipal oficial quanto pelas referências estaduais<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<p>Socorro foi atingida por chuvas fortes em dezembro de 2023 e em janeiro de 2024, tendo essa última alcançado, em duas horas, 100 milímetros de água, com pontes, ruas e áreas danificadas. Um dos pontos alagados foi a Unidade Básica de Saúde (UBS), com atendimento interrompido à população. A estância turística do Circuito das Águas também ficou debaixo das águas e as 100 (cem) famílias desabrigadas foram alojadas no ginásio de esportes. A chuva alagou a região central e diversos bairros periféricos, tendo sido decretada situação de emergência pelo município. Uma das principais fontes de renda do município é a produção de malhas construída por pequenas empresas familiares, com uma cadeia de produção que movimenta o turismo, principalmente, no inverno e reflete positivamente em serviços de bares, hotéis e restaurantes. Devido às inundações ocorridas, além do comércio de malhas propriamente dito, toda a prestação de serviços dos diversos setores atrelados ao turismo de malhas sofreu prejuízos.</p>
<p>Por seu turno, Artur Nogueira&nbsp;é um&nbsp;município integrante da&nbsp;<a href="https://pt.wikipedia.org/wiki/Regi%C3%A3o_Metropolitana_de_Campinas">Região Metropolitana de Campinas</a>. Localiza-se a uma&nbsp;<a href="https://pt.wikipedia.org/wiki/Latitude">latitude</a>&nbsp;22º 34'23"&nbsp;<a href="https://pt.wikipedia.org/wiki/Sul">Sul</a>&nbsp;e a uma&nbsp;<a href="https://pt.wikipedia.org/wiki/Longitude">longitude</a>&nbsp;47º 10'21"&nbsp;<a href="https://pt.wikipedia.org/wiki/Oeste">Oeste</a>, estando a uma&nbsp;<a href="https://pt.wikipedia.org/wiki/Altitude">altitude</a>&nbsp;de 588 metros. Sua população, de acordo com o&nbsp;<a href="https://pt.wikipedia.org/wiki/Censo_demogr%C3%A1fico_do_Brasil_de_2022">Censo 2022 (IBGE)</a>,&nbsp;era de 51&nbsp;456 habitantes, possuindo uma área de 178,026km². O município é conhecido como Berço da Amizade<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Os setores econômicos que, atualmente, mais reúnem trabalhadores são os do comércio varejista, da fabricação de produtos de produto têxteis e da administração pública e defesa e seguridade social. Tem como principais corpos d´água o Rio Piratingui, ou o rio dos peixes vermelhos, o Ribeirão Boa Vista, o Ribeirão das Três Barras, o Ribeirão do Monjolo Grande e o Ribeirão dos Pires. Possui, ainda, três represas dentro do perímetro urbano, sendo estas em áreas públicas. O município também possui uma grande quantidade de represas rurais, usadas para fins agrícolas, de irrigação ou piscicultura ou com fins ornamentais, sendo que a captação de água para o abastecimento público é feita na Represa do Ribeirão dos Pires. Além disso, possui inúmeros córregos e ainda e muitas grotas. A cidade integra o Consórcio das Bacias dos rios&nbsp;<a href="https://pt.wikipedia.org/wiki/Rio_Piracicaba_(S%C3%A3o_Paulo)">Piracicaba</a>,&nbsp;<a href="https://pt.wikipedia.org/wiki/Rio_Capivari_(Tiet%C3%AA)">Capivari</a>&nbsp;e&nbsp;<a href="https://pt.wikipedia.org/wiki/Rio_Jundia%C3%AD">Jundiaí</a><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<p>Em junho de 2024, Artur Nogueira decretou estado de crise hídrica e estabeleceu racionamento e a administração pública local passou a diminuir a pressão nas redes de água em horários específicos. O manancial que abastece a cidade estava em 40% do total de disponibilidade hídrica. Por conta da falta de chuvas e da redução considerável dos níveis da represa que abastece a cidade, a prefeitura decretou&nbsp;"estado de crise hídrica"&nbsp;e estabeleceu uma série de medidas para tentar evitar que o município passasse por uma situação ainda mais drástica de falta d'água. Entre as medidas técnicas postas em curso, esteve a diminuição de pressão na rede de água, em horários específicos,&nbsp;o que a prefeitura já considera como uma prática de racionamento hídrico. Além do decreto de estado de crise hídrica, as autoridades locais – o prefeito municipal, a partir das recomendações da defesa civil –, também decretaram “situação de emergência” por conta da estiagem. Consta que a represa Cotrins, principal fonte de captação de água da cidade, esteve, à época, com&nbsp;"nível precário",&nbsp;de 1,65m abaixo do normal e, caso chegasse a 1,80m abaixo do normal, o manancial já atingiria o&nbsp;volume morto. Além do racionamento, também foi determinado a suspensão da captação de água da represa Cotrins por duas horas por dia, na tentativa de recuperação do nível da lagoa<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>.</p>
<p>Os aspectos acima foram contemplados, ainda que de forma superficial, pelos veículos de comunicação que se interessaram na cobertura de ambas as emergências e cujas matérias estão listadas na Tab.1, abaixo, e sobre cujos achados discorremos em seguida.</p>
<div class="text-center">
<p><strong>Tabela1</strong>: Matérias jornalísticas acerca das emergências ocorridas nos municípios de Socorro e de Artur Nogueira</p>
</div>
<table class="table">
<tbody>
<tr class="odd">
<td>ACidade ON Campinas. <a href="https://www.acidadeon.com/campinas/cotidiano/governo-de-sp-decreta-situacao-de-emergencia-em-artur-nogueira-devido-a-estiagem/">Governo de SP decreta situação de emergência em Artur Nogueira devido à estiagem</a>, 05 de agosto de 2024.</td>
</tr>
<tr class="even">
<td>ACidade ON Campinas. <a href="https://www.acidadeon.com/campinas/cotidiano/temporal-alaga-bairros-de-socorro-e-deixa-100-familias-desabrigadas-estado-envia-ajuda/">Temporal alaga bairros de Socorro e deixa 100 famílias desabrigadas; Estado envia ajuda. Em duas horas de temporal, foram registrados 130 milímetros de chuva. Ao menos 100 famílias foram atingidas por alagamentos</a>, 21 de agosto de 2024.</td>
</tr>
<tr class="odd">
<td>BAND MULTI - Campinas e região. <a href="https://www.band.uol.com.br/band-multi/campinas-e-regiao/noticias/pelo-menos-200-familias-sao-atingidas-por-enchente-em-socorro-16661888">Pelo menos 200 famílias são atingidas por enchente em Socorro. Auxílio aos desabrigados está sendo prestado no Ginásio de Esportes da cidade</a>, 22 de janeiro de 2024.</td>
</tr>
<tr class="even">
<td>CBN CAMPINAS 99.1 FM. <a href="https://portalcbncampinas.com.br/2024/01/mais-de-450-pessoas-foram-afetadas-pelas-fortes-chuvas-em-socorro/">Mais de 450 pessoas foram afetadas pelas fortes chuvas em Socorro</a>, 23 de janeiro de 2024.</td>
</tr>
<tr class="odd">
<td>G1 CAMPINAS E REGIÃO EPTV. <a href="https://g1.globo.com/sp/campinas-regiao/noticia/2024/01/21/chuva-deixa-socorro-embaixo-dagua-e-atinge-100-familias-estado-envia-ajuda-humanitaria.ghtml">Chuva deixa Socorro embaixo d’água e atinge 100 famílias; estado envia ajuda humanitária. Ginásio de Esporte vai receber desabrigados. Em duas horas, cidade registrou 100 milímetros de água. Pontes foram danificadas e árvores caíram</a>, 21 de janeiro de 2024.</td>
</tr>
<tr class="even">
<td>G1 CAMPINAS E REGIÃO EPTV. <a href="https://g1.globo.com/sp/campinas-regiao/noticia/2024/08/05/crise-hidrica-governo-estadual-decreta-situacao-de-emergencia-em-artur-nogueira.ghtml">Crise hídrica: governo estadual decreta situação se emergência em Artur Nogueira. Decreto foi publicado nesta segunda-feira (5) e tem validade de 180 dias. Estado também determinou desassoreamento do córrego Cotrins e envio de 25 mil litros d´água à cidade</a>, 05 de agosto de 2024.</td>
</tr>
<tr class="odd">
<td>G1 CAMPINAS E REGIÃO EPTV. <a href="https://g1.globo.com/sp/campinas-regiao/noticia/2024/07/31/em-crise-hidrica-artur-nogueira-recebe-da-forca-aerea-agua-que-iria-para-o-sul-e-tenta-evitar-colapso-em-escolas-e-centros-de-saude.ghtml">Em crise hídrica, Artur Nogueira recebe da Força Aérea água que iria para o Sul e tenta evitar colapso em escolas e centros de saúde</a>, 31 de julho de 2024.</td>
</tr>
<tr class="even">
<td>G1 CAMPINAS E REGIÃO EPTV. <a href="https://g1.globo.com/sp/campinas-regiao/noticia/2024/01/22/em-estado-de-emergencia-socorro-tem-204-familias-atingidas-por-enchente.ghtml">Socorro tem 204 famílias atingidas por enchente em chuva mais intensa dos últimos 36 anos. Ginásio de Esportes recebeu 14 famílias desalojadas. Prefeitura trabalha na limpeza dos locais nesta segunda-feira. Estado enviou ajuda humanitária. Chuva de sábado deixou a cidade embaixo d’água</a>, 22 de janeiro de 2024.</td>
</tr>
<tr class="odd">
<td>GOV.BR. Ministério da Integração e do Desenvolvimento Regional. <a href="https://www.gov.br/mdr/pt-br/noticias/artur-nogueira-e-sao-pedro-do-turvo-em-sao-paulo-obtem-reconhecimento-federal-de-situacao-de-emergencia-devido-a-estiagem">Artur Nogueira e São Pedro do Turvo, em São Paulo, obtêm reconhecimento federal de situação de emergência devido à estiagem. Agora, municípios podem solicitar recursos do Governo Federal para ações de defesa civil</a>, 28 de agosto de 2024.</td>
</tr>
<tr class="even">
<td>HORA CAMPINAS. <a href="https://horacampinas.com.br/fortes-chuvas-causam-estragos-em-socorro-100-familias-sao-atingidas/">Fortes chuvas causam estragos em Socorro; 100 famílias são atingidas. Cidade pede ajuda à Defesa Civil do Estado para atender os desalojados</a>, 21 de janeiro de 2024.</td>
</tr>
<tr class="odd">
<td>JNO. JORNAL DE NOVA ODESSA. <a href="https://www.jornaldenovaodessa.com.br/noticias/estado-faz-intervencao-com-desassoreamento-contra-situacao-de-seca-e-estiagem-severa-na-regiao/">Estado faz intervenção com desassoreamento contra situação de seca e estiagem severa na região. Governo paulista iniciou ações de apoio a Artur Nogueira, afetada pela estiagem na Região Metropolitana de Campinas; medidas de desassoreamento do córrego Cotrins a serem realizadas nesta semana</a>, 07 de agosto de 2024</td>
</tr>
<tr class="even">
<td>JORNAL BRAGANÇA. <a href="https://jornalmaisbraganca.com.br/2024/01/21/socorro-e-atingida-por-temporal-e-sofre-com-alagamentos/">Socorro é atingida por temporal e sofre com alagamentos</a>, 21 de janeiro de 2024.</td>
</tr>
<tr class="odd">
<td>JORNAL DA EPTV 1ª Edição - Campinas/Piracicaba. <a href="https://globoplay.globo.com/v/12287478/">Socorro (SP) entra em situação de emergência após enchente. Prefeitura decretou estado de emergência e estado enviou ajuda humanitária ao município</a>, 22 de janeiro de 2024.</td>
</tr>
<tr class="even">
<td>JORNAL TROMBETA. <a href="https://www.jornaltrombeta.com.br/noticia/seca-governo-decreta-situacao-de-emergencia-no-interior-de-sp">Seca: governo decreta situação de emergência no interior de SP. Artur Nogueira, no interior, está em situação de emergência por causa da crise hídrica no município. Seca também afeta outras regiões</a>, 05 de agosto de 2024.</td>
</tr>
<tr class="odd">
<td>PLANTÃO BRASIL. <a href="https://www.plantaobrasil.net/news.asp?nID=142107">Grave situação de seca no interior de SP leva governador a decretar estado de emergência</a>, 05 de agosto de 2024.</td>
</tr>
<tr class="even">
<td>RADIO BANDEIRANTES FM. <a href="https://www.youtube.com/watch?v=R2kyrl7ExdM">Socorro (SP) registra 130 mm de chuva, Prefeitura decreta emergência</a>, 22 de janeiro de 2024</td>
</tr>
<tr class="odd">
<td>SÃO PAULO. Governo do Estado. São Paulo para todos. <a href="https://www.agenciasp.sp.gov.br/governo-de-sp-inicia-acoes-de-apoio-a-artur-nogueira-afetada-pela-estiagem/">Governo de SP inicia ações de apoio a Artur Nogueira, afetada pela estiagem. Medidas de desassoreamento do córrego Cotrins começaram nesta segunda-feira (5)</a>, 05 de agosto de 2024.</td>
</tr>
<tr class="even">
<td>SEMIL - Secretaria de Meio Ambiente, Infraestrutura e Logística de SP. <a href="https://semil.sp.gov.br/2024/08/governo-de-sp-executa-acoes-de-apoio-a-artur-nogueira-afetada-pela-estiagem/">Governo de SP executa ações de apoio a Artur Nogueira, afetada pela estiagem. Visita técnica foi realizada no sábado (3) e ações de desassoreamento do Cotrins fazem parte do programa São Paulo Sempre Alerta</a>, 05 de agosto de 2024.</td>
</tr>
<tr class="odd">
<td>SOUZA, Luis Eduardo de. <a href="https://correio.rac.com.br/campinasermc/estado-mobiliza-recursos-para-aliviar-seca-em-a-nogueira-1.1547548">Estado mobiliza recursos para aliviar seca em A. Nogueira. Conjunto de medidas inclui desassoreamento da represa que abastece a cidade</a>. Correio Popular, 06 de agosto de 2024.</td>
</tr>
<tr class="even">
<td>TODO DIA CAMPINAS SAMPI. <a href="https://sampi.net.br/campinas/noticias/2849096/campinas/2024/08/estado-decreta-situacao-de-emergencia-em-artur-nogueira">Estado decreta situação de emergência em Artur Nogueira</a>, 06 de agosto de 2024.</td>
</tr>
<tr class="odd">
<td>VTV DA GENTE. <a href="https://www.facebook.com/watch/?v=1164081134875308&amp;paipv=0&amp;eav=AfaGw3RKSsu1FesY03pTHFblOOijoTT-WRsW6O9ktuo1oUzKWor1bzspXbN8O79bcxc&amp;_rdr">Crise Hídrica em Artur Nogueira. Cidade recebe doações para escolas e unidades de saúde</a>, 06 de agosto de 2024.</td>
</tr>
</tbody>
</table>
<div class="text-center">
<p><strong>Elaboração:</strong> as autoras.</p>
</div>
<p>Conforme observado pelos achados jornalísticos apresentados no Quadro 1, abaixo, no que concerne ao plano territorial da vivência destes dois tipos de emergência recentemente ocorridas no interior paulista, respectivamente em Socorro e em Artur Nogueira, inundações e crises hídricas, a concretização do fator de ameaça exigiu o deslocamento das pessoas de seu território de vivência e/ou de trabalho, como ocorre em situações semelhantes em outras localidades do país (VALENCIO, 2019). No caso de Socorro, estruturas móveis e imóveis foram danificadas ou destruídas e as pessoas (moradores, trabalhadores, empresários, clientes) nelas inseridas e a elas vinculadas não puderam permanecer em razão do risco iminente à vida e à saúde naquelas circunstâncias. No caso de Artur Nogueira, perderam tudo aquilo que dependia de água para sobreviver, de plantas a animais de criação, além de atividades econômicas e domésticas, cujo exercício foi inviabilizado, tais como o funcionamento de lava-rápidos, de bares e restaurantes, higienização residencial e corporal, o que induziu moradores a despenderem recursos financeiros extraordinários para acessar provimentos hídricos alternativos ou se deslocarem para outras localidades, como residência de parentes e amigos, para lidar com algumas de suas necessidades hídricas emergenciais. Serviços cuja oferta foi inviabilizada fez desaparecer os potenciais clientes e/ou fregueses, com decorrentes perdas de fluxo de caixa e receita necessária para cobrir gastos fixos e variáveis, de aluguéis a salários e fornecedores.</p>
<p>No plano material, muitos bens móveis/imóveis, de uso público ou privado, sofreram danificação ou perda total em decorrência de inundações, implicando que objetos neles contidos – tais como instrumentos e ferramentas de trabalho e/ou utensílios relacionados a atividades extraeconômicas – foram igualmente danificados ou destruídos. Isso produziu efeitos deletérios nas rotinas da moradia, do ambiente de trabalho, de utilização de veículo automotivo, de equipamento computacional e escolar, dentre outros (VALENCIO, N e VALENCIO, A., 2018a).</p>
<p>Em relação ao âmbito econômico, que está interligado aos anteriores, enfatiza-se o campo trabalho, formal e informal, e da obtenção de renda para a garantia dos mínimos vitais e sociais, na realização do consumo e viabilidade da produção e circulação de bens. Significa que o discurso jornalísticos deveria ter uma abordagem voltada para a verificação da existência de condições alternativas de trabalho, se trabalhadores permanecem executando o seu trabalho e através de quais novas e precárias estratégias como o fazem, se as condições de obter renda são em patamares compatíveis com os tempos regulares instituídos em sua jornada formal, se existem políticas de proteção social acessíveis para aqueles que se encontram em situação de vulnerabilidade extrema nessas circunstâncias, como o auxílio emergencial, se há outros modos de produção e circulação de bens ou serviços, seja naquela mesma localidade ou mesmo em outra escala de abrangência das atividades econômicas (FERGUSON, 2021; FIELDS, 2023).</p>
<p>Em relação à dimensão simbólica, seja no campo da materialidade, da espacialidade, aa vida econômica ou mesmo da vida social cotidiana, a forma como o sujeito afetado interpreta essa perda repercute como ferida emocional, que atinge o sentido de propósito da vida, o sentido do próprio eu, na constituição da sua identidade, nas suas relações de natureza espiritual, o que se traduz em singularidades da experiência de sofrimento que a mídia profissional tem tido mais sensibilidade para capturar, dado o apelo da empatia que seu público possa vir a ter com aquele sujeito. Porém, são perdas multifacetadas que nem sempre o discursos jornalístico valoriza. Há perdas do objeto de memória, de fotografias, de objetos de valor afetivo, de objetos religiosos de grande significação no entendimento de si no mundo (DAS, 2020; DOUGLAS, 2007).</p>
<p>Por fim, há dimensão social e contextos de inundações e de crise hídrica podem comprometer o enredamento público e privado da vida cotidiana do sujeito, esgarçando-os, algo que exigiria um olhar mais atento da prática jornalística de abordagem aos sujeitos afetados na localidade em desastres. Há rompimento nas rotinas de encontro e exercício de papeis socias complementares, nas rotinas de relações afetivas – seja por conta do desaparecimento de entes queridos, seja porque uma parte da comunidade se mudou, definitiva ou circunstancialmente, para outra localidade – e os laços de convivência e vizinhança foram se desfazendo (TURNER, 2012). Segundo Das (2007), a linguagem dos sujeitos em sofrimento tem de expressar a historicidade das suas vidas, por meio dos discursos que apresentam as subjetividades implicadas, numa realidade de dor e injustiça, e que pode alcançar a forma de resistência (noutras, silenciadas por opressões explícitas ou tácitas).</p>
<p>Os aspectos acima foram explorados em registros jornalísticos simplificadores desses dramas, reduzindo o tamanho da condição humana dos que os vivenciaram e, por conseguinte, orientaram providências públicas comezinhas aos que os podiam – e deviam – compensar ou reparar tais situações entretecidas de sofrimento social (AMARAL <em>et al.</em>, 2010; BARRIOS, 2017). Salienta-se que as menções aos jornais indicadas abaixo podem ser todas retiradas das referências, pois já estão na tabela 1</p>
<div class="text-center">
<p><strong>Quadro 1:</strong> Dimensões de perdas, danos e providências públicas nos casos de Socorro e Artur Nogueira, segundo os registros jornalísticos acessados</p>
<hr>
<table class="table">
<colgroup>
<col style="width: 31%">
<col style="width: 31%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Dimensão/Contexto local</strong></th>
<th><p><strong>Emergência relacionada ao estresse hídrico</strong></p>
<p><strong>(Caso Artur Nogueira)</strong></p></th>
<th><p><strong>Emergência relacionada a chuvas intensas</strong></p>
<p><strong>(Caso Socorro)</strong></p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Econômico -financeira-material</td>
<td><p><strong>5 menções na imprensa</strong></p>
<p>Impossibilidade/ limitação de funcionamento de escolas, comércio, aparelhos públicos</p></td>
<td><p><strong>11 menções</strong></p>
<p>Danificação de malharias, equipamentos, lojas e casas</p>
<p>Prejuízo da rede hoteleira e restaurante</p></td>
</tr>
<tr class="even">
<td>Rotinas da vida doméstica e pessoal</td>
<td><p><strong>5 menções na imprensa</strong></p>
<p>Inviabilidade da higienização da casa, higienização corporal, e demais atos diários, como cozinhar</p></td>
<td><p><strong>3 menções</strong></p>
<p>Sobre inundação de escolas e hospitais, afetando diretamente a rotina dos moradores</p></td>
</tr>
<tr class="odd">
<td>Psicossocial</td>
<td><strong>Nenhuma referência</strong></td>
<td><p><strong>1 menção</strong></p>
<p>Desalento de costureira e de uma cabelereira que perderam casa, salão e a tristeza devido ao evento hídrico</p></td>
</tr>
<tr class="even">
<td>Ambiental (impressões sobre o entorno)</td>
<td><p><strong>14 menções na imprensa</strong></p>
<p>Quantidade de tempo que a cidade está em estiagem, que não chove na cidade, tampouco em cidades próximas, fotos de rios e córregos que secam</p></td>
<td><p><strong>11 menções</strong></p>
<p>Fotos das inundações, ruas alagadas, carros arrastados, pessoas tirando a lama das casas e do comércio, com destaque para a quantidade de ml de chuva em poucas horas</p></td>
</tr>
<tr class="odd">
<td>Destaque para as medidas/soluções propostas pelo Poder publico</td>
<td><strong>14 menções</strong> sobre as medidas que já foram tomadas e outras que serão tomadas pelo Poder Público, além das doações ofertadas pelos entes públicos, como água e caminhões pipa. Ajuda financeira de outras esferas públicas para construção de represas, de poços</td>
<td><strong>11 menções</strong> sobre as medidas que serão tomadas, construção de piscinões, o abrigo em ginásios de esporte, a doação de alimentos e roupas de toda parte do país, ajuda financeira de outras esferas públicas</td>
</tr>
</tbody>
</table>
<hr>
<p><strong>Elaboração:</strong> as autoras</p>
</div>
</section>
<section id="conclusões" class="level3">
<h3 class="anchored" data-anchor-id="conclusões"><strong>Conclusões</strong></h3>
<p>Em comparação com a possibilidade de aceder privilegiadamente espaços e pessoas em meio à fase mais aguda de emergências, o olhar jornalístico da grande mídia ou de mídias profissionais locais ainda tem sido tímido para explorar a multidimensionalidade do sofrimento social e a problemática da qualidade das providências públicas que foram tomadas na ocasião ou que se deixou de fazê-lo.</p>
<p>Diante o caso das inundações ocorridas no município de Socorro/SP, viu-se o destaque das matérias jornalísticas às perdas econômicas – portanto, à esfera da vida pública comunitária –, enquanto que, em Artur Nogueira, foi ressaltado o âmbito da vida cotidiana nos afazeres domésticos (limpeza doméstica interna e externa; lavagem de vestuário e afins) e de satisfação de necessidades vitais (comprometimento das condições regulares de dessedentação humana e animal, higienização corporal, cocção de alimentos e afins).</p>
<p>Destaque também houve, nos registros jornalísticos analisados, às providências de resposta que as autoridades públicas e o meio técnico tomaram uma vez declarada a emergência, deixando-se de explorar mais detidamente as razões pelas quais as estratégias preventivas e preparativas que pudessem ter evitado ou mitigado tais danos e prejuízos não foram tomadas no tempo devido, isto é, no período anterior à manifestação de tais eventos. Em ambos os casos, tratar-se-ia de providências infraestruturais relacionadas à drenagem urbana (caso de Socorro) e aumento da reservação antecipada de água para fins de abastecimento em época de estiagem (caso de Artur Nogueira). O fato de serem ambos municípios de médio porte – Socorro no estrato 4, de 20.001 até 50 mil habitantes, e Artur Nogueira no estrato 5, de 50.001 até 100 mil habitantes – lhes poderia dar as condições institucionais e técnicas necessárias para saber captar preventivamente os recursos necessários para tais obras de grande envergadura. Mas, essa discussão foi posta de lado na interpretação jornalística da situação. Por fim, a diversidade dos modos de vida dos sujeitos em sofrimento nessas circunstância poderia ter sido mais bem apresentado ao público para que os modos correspondentes de enfrentamento da situação e de sofrimento social pudessem ter sido igualmente ressaltados, ampliando, assim, a compreensão pública sobre a multidimensionalidade destas crises.</p>
<div class="text-center">
<p><strong>AGRADECIMENTOS</strong></p>
<p>N.V. agradece à Fapesp, processo número 2022/09136-1 e ao CNPq, pelo apoio na forma de Bolsa de Produtividade, processo número 316828/2023-8.</p>
<p>C.M.F.B. agradece à CAPES pela Bolsa de Doutorado.</p>
</div>
</section>
<section id="referências" class="level3">
<h3 class="anchored" data-anchor-id="referências"><strong>Referências</strong></h3>
<p>AMARAL, Márcia Franz; POZOBON, Rejane de Oliveira; RUBIN, Anaqueli. Modos de endereçar a tragédia: indignação, testemunho e piedade. <em>Lumina</em>, v. 4, n.2, 2010, p.&nbsp;1-15.</p>
<p>BARRIOS, Marta Milena; CABRERA, Jesús Arroyave e VEGA-ESTARITA, Lina. El cambio de paradigma en la cobertura informativa de la gestión de riesgo de desastres. <em>Chasqui: Revista Latinoamericana de Comunicación</em>, n. 136, 2017, p.&nbsp;129-144.</p>
<p>BARROS, José D’Assunção. “Fixos e fluxos: revisitando um par conceitual.” <em>Cuadernos de Geografía: Revista Colombiana de Geografía</em>, v. 29, n.&nbsp;2, p.&nbsp;493-504, jul-dez de 2020.</p>
<p>BIASOLI, F.; BIASOLI, S. <a href="https://diplomatique.org.br/tragedia-crime-litoral-norte-sao-paulo-chuvas/">Um ano da tragédia-crime no litoral norte de São Paulo</a>. <em>Le Monde Diplomatique Brasil</em>, 17 de fevereiro de 2024.</p>
<p>BRAGA, M. S. S.; COSTA, V. M.; FERNANDES, J. L. Dinâmicas de funcionamento e controle do poder nos partidos políticos: os casos do PT e PSDB no Estado de São Paulo. <em>Revista Brasileira de Ciências Sociais.</em> 2018. 33(96):1-26.</p>
<p>BRASIL. Ministério da Integração e do Desenvolvimento Regional, Defesa Civil. <a href="https://www.gov.br/mdr/pt-br/noticias/artur-nogueira-e-sao-pedro-do-turvo-em-sao-paulo-obtem-reconhecimento-federal-de-situacao-de-emergencia-devido-a-estiagem"><em>Artur Nogueira e São Pedro do Turvo, em São Paulo, obtêm reconhecimento federal de situação de emergência devido à estiagem</em></a>, 28 de agosto de 2024.</p>
<p><a href="https://g1.globo.com/sp/campinas-regiao/noticia/2024/01/21/chuva-deixa-socorro-embaixo-dagua-e-atinge-100-familias-estado-envia-ajuda-humanitaria.ghtml">CHUVA deixa Socorro embaixo d’água e atinge 100 famílias; estado envia ajuda humanitária. Ginásio de Esporte vai receber desabrigados</a>. <em>G1 Campinas e região EPTV</em>, 21 de janeiro de 2024.</p>
<p><a href="https://www.facebook.com/watch/?v=1164081134875308&amp;paipv=0&amp;eav=AfaGw3RKSsu1FesY03pTHFblOOijoTT-WRsW6O9ktuo1oUzKWor1bzspXbN8O79bcxc&amp;_rdr">CRISE Hídrica em Artur Nogueira. Cidade recebe doações para escolas e unidades de saúde</a>. <em>VTV da gente</em>, 06 de agosto de 2024.</p>
<p><a href="https://g1.globo.com/sp/campinas-regiao/noticia/2024/08/05/crise-hidrica-governo-estadual-decreta-situacao-de-emergencia-em-artur-nogueira.ghtml">CRISE hídrica: governo estadual decreta situação se emergência em Artur Nogueira. Decreto foi publicado nesta segunda-feira (5) e tem validade de 180 dias</a>. <em>G1 Campinas e região EPTV</em>, 05 de agosto de 2024.</p>
<p>DAS, Veena. <em>Vida e palavras. A violência e sua descida ao ordinário</em>. São Paulo. Ed. Unifesp. 2020, 312 págs.</p>
<p>DOUGLAS, Mary. O mundo dos bens, vinte anos depois. <em>Horizontes Antropológicos</em>, Porto Alegre, ano 13, n.&nbsp;28, p.&nbsp;17-32, jul./dez. 2007.</p>
<p><a href="https://g1.globo.com/sp/campinas-regiao/noticia/2024/07/31/em-crise-hidrica-artur-nogueira-recebe-da-forca-aerea-agua-que-iria-para-o-sul-e-tenta-evitar-colapso-em-escolas-e-centros-de-saude.ghtml">EM crise hídrica, Artur Nogueira recebe da Força Aérea água que iria para o Sul e tenta evitar colapso em escolas e centros de saúde</a>. <em>G1 CAMPINAS E REGIÃO EPTV</em>, 31 de julho de 2024.</p>
<p><a href="https://sampi.net.br/campinas/noticias/2849096/campinas/2024/08/estado-decreta-situacao-de-emergencia-em-artur-nogueira">ESTADO decreta situação de emergência em Artur Nogueira</a>. <em>Todo dia Campinas Sampi</em>. 06 de agosto de 2024.</p>
<p><a href="https://www.jornaldenovaodessa.com.br/noticias/estado-faz-intervencao-com-desassoreamento-contra-situacao-de-seca-e-estiagem-severa-na-regiao">ESTADO faz intervenção com desassoreamento contra situação de seca e estiagem severa na região. Governo paulista iniciou ações de apoio a Artur Nogueira, afetada pela estiagem na Região Metropolitana de Campinas; medidas de desassoreamento do córrego Cotrins a serem realizadas nesta semana</a>. <em>JNO. Jornal de Nova Odessa</em>, 07 de agosto de 2024.</p>
<p>FERGUSON, Niall. <em>Catástrofe: uma história dos desastres – das guerras às pandemias – e o nosso fracasso em aprender como lidar com eles</em>. São Paulo: Planeta, 2021.</p>
<p>FIELDS, Desirée. Speculative urbanism. <em>Environment and Planning A: Economy and Space</em>. Los Angeles, v. 55, n.2, 2023, p.&nbsp;511–516.</p>
<p>FORTES chuvas causam estragos em Socorro; 100 famílias são atingidas. Cidade pede ajuda à Defesa Civil do Estado para atender os desalojados. <em>Hora Campinas</em>, 21 de janeiro de 2024. Disponível em: https://horacampinas.com.br/fortes-chuvas-causam-estragos-em-socorro-100-familias-sao-atingidas/</p>
<p><a href="https://www.jornaltrombeta.com.br/noticia/seca-governo-decreta-situacao-de-emergencia-no-interior-de-sp">GOVERNO decreta situação de emergência no interior de SP. Artur Nogueira, no interior, está em situação de emergência por causa da crise hídrica no município. Seca também afeta outras regiões</a>. <em>Jornal Trombeta</em>, 05 de agosto de 2024.</p>
<p><a href="https://www.acidadeon.com/campinas/cotidiano/governo-de-sp-decreta-situacao-de-emergencia-em-artur-nogueira-devido-a-estiagem/">GOVERNO de SP decreta situação de emergência em Artur Nogueira devido à estiagem</a>. <em>ACIDADEon Campinas</em>, 05 de agosto de 2024.</p>
<p><a href="https://www.plantaobrasil.net/news.asp?nID=142107">GRAVE situação de seca no interior de SP leva governador a decretar estado de emergência</a>. <em>Plantão Brasil</em>, 05 de agosto de 2024.</p>
<p>HELLER, Léo. <em>The human rights to water and sanitation.</em> Cambridge: Cambridge University Press, 2022.</p>
<p>KOWARICK, Lucio. <em>Viver em risco: sobre a vulnerabilidade socioeconômica e civil</em>. São Paulo: Editora 34, 2009.</p>
<p><a href="https://portalcbncampinas.com.br/2024/01/mais-de-450-pessoas-foram-afetadas-pelas-fortes-chuvas-em-socorro/">MAIS de 450 pessoas foram afetadas pelas fortes chuvas em Socorro</a>. <em>CBN CAMPINAS 99.1 FM</em>, 23 de janeiro de 2024.</p>
<p>MARENGO, J.A.; ALVES, L. M. Crise hídrica em São Paulo em 2014: seca e desmatamento. <em>Rev.&nbsp;GEOUSP.</em> Espaço e Tempo, v. 19, n.&nbsp;3, 2015, 485-494.</p>
<p><a href="https://www.band.uol.com.br/band-multi/campinas-e-regiao/noticias/pelo-menos-200-familias-sao-atingidas-por-enchente-em-socorro-16661888">PELO menos 200 famílias são atingidas por enchente em Socorro. Auxílio aos desabrigados está sendo prestado no Ginásio de Esportes da cidade</a>. <em>BAND MULTI - Campinas e região,</em> 22 de janeiro de 2024.</p>
<p>SÃO PAULO. Governo do Estado. <em>SÃO PAULO para todos</em>. <a href="https://www.jornaldeuberaba.com.br/noticia/87505/governo-de-sp-inicia-acoes-de-apoio-a-artur-nogueira-afetada-pela-estiagem">Governo de SP inicia ações de apoio a Artur Nogueira, afetada pela estiagem. Medidas de desassoreamento do córrego Cotrins começaram nesta segunda-feira (5)</a>, 05 de agosto de 2024.</p>
<p>SÃO PAULO. Secretaria de Meio Ambiente, Infraestrutura e Logística de SP. <em>SEMIL</em>. <a href="https://semil.sp.gov.br/2024/08/governo-de-sp-executa-acoes-de-apoio-a-artur-nogueira-afetada-pela-estiagem/">Governo de SP executa ações de apoio a Artur Nogueira, afetada pela estiagem. Visita técnica foi realizada no sábado (3) e ações de desassoreamento do Cotrins fazem parte do programa São Paulo Sempre Alerta</a>, 05 de agosto de 2024.</p>
<p>SCANLON, Joseph; ALLDRED, Suzanne. <em>Media Coverage of Disasters: The Same Old Story</em>. Ljubljana (Yugoslavia): Technical Report Paper.</p>
<p><a href="https://www.jornaltrombeta.com.br/noticia/seca-governo-decreta-situacao-de-emergencia-no-interior-de-sp">SECA: governo decreta situação de emergência no interior de SP. Artur Nogueira, no interior, está em situação de emergência por causa da crise hídrica no município</a>. <em>Jornal Trombeta</em>, 05 de agosto de 2024.</p>
<p><a href="https://jornalmaisbraganca.com.br/2024/01/21/socorro-e-atingida-por-temporal-e-sofre-com-alagamentos/">SOCORRO é atingida por temporal e sofre com alagamentos</a>. <em>Jornal Bragança</em>, 21 de janeiro de 2024.</p>
<p><a href="https://globoplay.globo.com/v/12287478/">SOCORRO (SP) entra em situação de emergência após enchente. Prefeitura decretou estado de emergência e estado enviou ajuda humanitária ao município</a>. <em>Jornal da EPTV 1ª Edição - Campinas/Piracicaba</em> 22 de janeiro de 2024.</p>
<p><a href="https://www.youtube.com/watch?v=R2kyrl7ExdM">SOCORRO (SP) registra 130 mm de chuva, Prefeitura decreta emergência</a>. <em>Radio Bandeirantes</em>, 22 de janeiro de 2024.</p>
<p><a href="https://g1.globo.com/sp/campinas-regiao/noticia/2024/01/22/em-estado-de-emergencia-socorro-tem-204-familias-atingidas-por-enchente.ghtml">SOCORRO tem 204 famílias atingidas por enchente em chuva mais intensa dos últimos 36 anos. Ginásio de Esportes recebeu 14 famílias desalojadas</a>. <em>G1 CAMPINAS E REGIÃO EPTV</em>, 22 de janeiro de 2024.</p>
<p>SOUZA, Luís Eduardo de. <a href="https://correio.rac.com.br/campinasermc/estado-mobiliza-recursos-para-aliviar-seca-em-a-nogueira-1.1547548">Estado mobiliza recursos para aliviar seca em A. Nogueira. Conjunto de medidas inclui desassoreamento da represa que abastece a cidade</a>. <em>Correio Popular</em>, Campinas, 06 de agosto de 2024.</p>
<p><a href="https://www.acidadeon.com/campinas/cotidiano/temporal-alaga-bairros-de-socorro-e-deixa-100-familias-desabrigadas-estado-envia-ajuda/">TEMPORAL alaga bairros de Socorro e deixa 100 famílias desabrigadas; Estado envia ajuda</a>. <em>A CIDADEOn Campinas</em>, 21 de agosto de 2024.</p>
<p>TUNDISI, José Galízia. Governança das águas. <em>Revista Universidade Federal de Minas Gerais, Belo Horizonte</em>, v. 20, n.2, p.&nbsp;222-235, jul./dez. 2013.</p>
<p>TURNER, Edith. <em>Communitas – The Anthropology of Collective Joy. New York</em>: Palgrave MacMillan, 2012.</p>
<p>VALENCIO, Norma; VALENCIO, Artur. O assédio em nome do bem: Dos sofrimentos conectados à dor moral coletiva de vítimas de desastres.&nbsp;Lumina. <em>Revista do Programa de Pós-Graduação em Comunicação da Universidade Federal de Juiz de Fora</em>&nbsp;<em>[S. l.]</em>, v. 12, n.&nbsp;2, p.&nbsp;19–39, 2018a.</p>
<p>VALENCIO, Norma; VALENCIO, Arthur. Media coverage of the ‘UK flooding crisis’: a social panorama. <em>Disasters</em>, v. 42, n.&nbsp;3, p.&nbsp;407-431, 2018b.</p>
<p>VALENCIO, Norma. Desastre como barbárie: o avesso do habitar. <em>Cadernos de Arquitetura e Urbanismo (online)</em>, v. 26, p.&nbsp;124-161, 2019.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Disponível em: <a href="https://www.ibge.gov.br/cidades-e-estados/sp/socorro.html" class="uri">https://www.ibge.gov.br/cidades-e-estados/sp/socorro.html</a>. Acesso em: 24 de agosto de 2024.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Disponível em: <a href="https://pt.wikipedia.org/wiki/Socorro_(munic%C3%ADpio)#:~:text=Socorro%20%C3%A9%20um%20munic%C3%ADpio%20brasileiro,era%20de%2041%20352%20habitantes.">Socorro (município) – Wikipédia, a enciclopédia livre</a>. Acesso em: 24 de agosto de 2024.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Disponível em: <a href="https://pt.wikipedia.org/wiki/Artur_Nogueira">Artur Nogueira – Wikipédia, a enciclopédia livre</a>. Acesso em: 24 de agosto de 2024.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Disponível em: <a href="https://pt.wikipedia.org/wiki/Artur_Nogueira">Artur Nogueira – Wikipedia, a enciclopédia livre</a>. Acesso em: 24 de agosto de 2024.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Disponível em: <a href="https://g1.globo.com/sp/campinas-regiao/noticia/2024/07/01/com-represa-em-nivel-precario-artur-nogueira-decreta-estado-de-crise-hidrica-e-estabelece-racionamento.ghtml">Com represa em nível 'precário', Artur Nogueira decreta estado de crise hídrica e estabelece racionamento | Campinas e Região | G1</a>. Acesso em: 27 de agosto de 2024.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Direitos humanos e a proteção do meio ambiente.html" class="pagination-link  aria-label=" direitos="" humanos="" e="" a="" proteção="" do="" meio="" ambiente:="" notas="" sobre="" o="" mercado="" interno="" regulado="" de="" carbono="" no="" brasil"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Direitos humanos e a proteção do meio ambiente: notas sobre o mercado interno regulado de carbono no Brasil</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Segurança pública_efetividade da polícia militar.html" class="pagination-link" aria-label="Segurança pública: efetividade da polícia militar por meio da ostensividade e do militarismo versus políticas públicas de policiamento comunitário em Manaus">
        <span class="nav-page-text">Segurança pública: efetividade da polícia militar por meio da ostensividade e do militarismo versus políticas públicas de policiamento comunitário em Manaus</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>ISBN: 978-65-85443-08-1 | © 2025 by CEDA</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>